### ISSUE TITLE
web3 CMS

### ISSUE THREAD

**Issue by 4x4notfound** [seidhr/muna-xyz#3]
Hi Tarje - I'm the cofounder of kubelt.com (web3 CMS). I came across this project and I was intrigued.

We're building a decentralized semantic graph and I'd like to discuss some opportunities if you're interested.

We're all hanging out on matrix here: https://matrix.to/#/#lobby:matrix.kubelt.com but you can also email me at adrian [at] kubelt.com

**Comment by tarjelavik** [comment]
Hi, sry, forgot to reply to your message :-/. Seems like you have made some changes to Kubelt, but the web3 space isn't really my cup of tea. Sry.
